modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
[[mods]]
modId="modulargolems"
version="${file.jarVersion}" #mandatory
displayName="Modular Golems" #mandatory
logoFile="modulargolems.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.modulargolems]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.modulargolems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modulargolems]]
    modId="l2library"
    mandatory=true
    versionRange="[1.4.0,)"
    ordering="AFTER"
    side="BOTH"