modLoader="javafml"
loaderVersion="[42,)"
license="All rights reserved"
[[mods]]
modId="modulargolems"
version="${file.jarVersion}" #mandatory
displayName="Modular Golems" #mandatory
logoFile="modulargolems.png" #optional
credits="LightLand team and Nulladev Team" #optional
authors="lcy0x1" #optional
description='''
This mod adds golems that can be crafted with different materials in a Tinker-like playstyle.
'''
[[dependencies.modulargolems]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.modulargolems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modulargolems]]
    modId="l2library"
    mandatory=true
    versionRange="[2.2.0,)"
    ordering="AFTER"
    side="BOTH"